### ISSUE TITLE
Like and Hint

### ISSUE THREAD

**Issue by martin-ger** [msillano/sonoff_watering#1]
Marco,

really like the project, the complete approach, the exhaustive description, and of cause the extensive use of the esp_mqtt.

Perhaps one hint. I recently had a student project with this kind of humidity sensors: they suffer from heavy corrosion and tend to fail after some weeks. There are better capacitive sensors with glass housing available - of course these are more expensive and not so easy to read...

**Comment by msillano** [comment]
Thanks, Martin

This is a low budget project... I also saw metallic probes covered with plaster ....
But here I do not need an accurate measurement: just a rough dry/soaked check.
I am studying, for accurate measurements of water conductivity, gold-plated probes with AC power supply.

I did some tests, then I made some changes: adding hysteresis to the comparator and polling (one minute) instead of the interrupt in mode 4 .... too many switchings near the threshold :(

Next: a simple timer for orchis and hidroponics watering (ebb and flow)

These projects are spin-offs of the main project: a professional modular control system for hydroponics ....

esp_mqtt if fun and wonderful :)

**Comment by msillano** [comment]
The new version (01.03.3) uses polling (in place of interrupt) for the  humidity sensors.
The probe-comparator circut is powered via GPIO-1, only 100 ms every minute.
That must reduce radically  the bad electrolytic effects on probe.
Thanks for the hint,
Best regards.
